language: android
dist: trusty
android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
before_install:
  - nvm install 12.14.0
  - cd template
  - node -v
  - npm i
  - npx sentry-wizard -i reactNative -p android --uninstall
  - gem install bundler
install:
  - bundle install
script:
  - fastlane android build
