matrix:
  include:
    - language: android
      dist: trusty
      android:
        components:
          # use the latest revision of Android SDK Tools
          - tools
          - platform-tools

          # The BuildTools version used by your project
          - build-tools-28.0.3

          # The SDK version used to compile your project
          - android-28

          # Additional components
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      before_install:
        - cd template
      install:
        - nvm install 12.14.0
        - npm i
        - npx sentry-wizard -i reactNative -p android --uninstall
        - gem install bundler
        - bundle install
      script:
        - fastlane android build
    - language: objective-c
      os: osx
      osx_image: xcode11.3
      before_install:
        - cd template
      install:
        - nvm install 12.14.0
        - gem install cocoapods
        - npm uninstall detox
        - npm i
        - npx sentry-wizard -i reactNative -p ios --uninstall
      before_script:
        - cd ios
        - pod install
      script:
        - xcodebuild -workspace HelloWorld.xcworkspace -scheme HelloWorld -sdk iphonesimulator -configuration Release | xcpretty && exit ${PIPESTATUS[0]}
